<<<<<<< HEAD
language:
- ruby
rvm:
- 2.5.1
cache:
- bundler
script:
- bundle install --jobs=3 --retry=3
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
env:
  global:
    -CC_TEST_REPORTER_ID=766e664dae0f727b6f668b11deec5c2516ffe52f9479a1b9eefdd1edbcba1dfa
after_script:
  - bundle exec rake coveralls:push
services:
- postgresql
=======
language: ruby
>>>>>>> f06a2ba75f5dd894a18dd4c0413207653e9d136e
deploy:
  provider: heroku
  api_key:
    secure: "f89c0e03-38f2-4f43-8da5-c4def5959043"
<<<<<<< HEAD
  app: acebook-cats
  on:
    repo: learningtocode101/acebook-team-cats
=======
>>>>>>> f06a2ba75f5dd894a18dd4c0413207653e9d136e
